#  Acceso a diferentes fuentes de datos

> **Antes de comenzar**
>
> Este laboratorio está diseñado para ejecutarse en **Google Colab**.
>
> Una vez abierto en Google Colab, ejecute la primera celda para clonar el repositorio del curso y acceder a los conjuntos de datos utilizados en este laboratorio.

In [1]:
!git clone https://github.com/urendacdenisse-hub/ingenieria-de-datos.git

Cloning into 'ingenieria-de-datos'...
remote: Enumerating objects: 640, done.
remote: Counting objects: 100% (293/293), done.
remote: Compressing objects: 100% (173/173), done.
remote: Total 640 (delta 137), reused 238 (delta 98), pack-reused 347 (from 1)
Receiving objects: 100% (640/640), 127.06 MiB | 22.71 MiB/s, done.
Resolving deltas: 100% (239/239), done.

In [2]:
%cd ingenieria-de-datos

/content/ingenieria-de-datos

## Introducción

En esta actividad practicarás diferentes formas de acceder a datos utilizando **archivos, bases de datos y APIs**.

Cada fuente requiere un mecanismo de acceso diferente. A lo largo de la actividad utilizarás los ejemplos vistos en el laboratorio para obtener datos desde cada una de ellas.


## Objetivo

Obtener datos desde diferentes fuentes utilizando Python.

- Leer datos almacenados en un archivo.
- Consultar información almacenada en una base de datos.
- Investigar y utilizar una API pública para obtener datos.

## Entregable

Completa las tres partes de la actividad directamente en el notebook.

Antes de entregar:

1. Ejecuta todas las celdas y verifica que no existan errores.
2. Asegúrate de que los resultados obtenidos sean visibles.
3. Guarda el notebook con un nombre apropiado.
4. Sube a la plataforma únicamente el archivo **`.ipynb`**.

In [3]:
# =================================================
# 🚫 NO MODIFICAR ESTA CELDA... O SE CREASHEA
# Configura todo lo necesario para comenzar
# =================================================

import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent.parent))

## Parte 1. Archivo

En el repositorio que acabas de clonar se encuentra el archivo **`fifa.csv`**, que contiene datos relacionados con la Copa Mundial de la FIFA.

El archivo se encuentra en la carpeta **`entrada`**, dentro de **`datos`**, en la carpeta **`ingenieria-de-datos`**.


1. Construir la ruta al archivo.
2. Leer el archivo CSV.
3. Elegir un número de filas a mostrar y muestra esa cantidad de registros del archivo.

In [5]:
# Importa la biblioteca necesarias
import pandas as pd

# Construye la ruta al archivo
ruta = "/content/ingenieria-de-datos/datos/entrada/fifa.csv"

# Lee el archivo CSV
df = pd.read_csv(ruta)
# Muestra los primeros x registros
df.head(4)

,match_id,world_cup_year,host_country,date,stage,round_raw,group,team1,team2,halftime_score_team1,...,extra_time_score_team1,extra_time_score_team2,penalty_score_team1,penalty_score_team2,winner,result_method,stadium,city,total_goals_team1,total_goals_team2
0,1,1930,Uruguay,1930-07-13,Group Stage,Matchday 1,Group 1,France,Mexico,3.0,...,NaN,NaN,NaN,NaN,France,Normal Time,Estadio Pocitos,Montevideo,4,1
1,2,1930,Uruguay,1930-07-15,Group Stage,Matchday 3,Group 1,Argentina,France,0.0,...,NaN,NaN,NaN,NaN,Argentina,Normal Time,Estadio Parque Central,Montevideo,1,0
2,3,1930,Uruguay,1930-07-16,Group Stage,Matchday 4,Group 1,Chile,Mexico,1.0,...,NaN,NaN,NaN,NaN,Chile,Normal Time,Estadio Parque Central,Montevideo,2,0
3,4,1930,Uruguay,1930-07-19,Group Stage,Matchday 7,Group 1,Chile,France,0.0,...,NaN,NaN,NaN,NaN,Chile,Normal Time,Estadio Centenario,Montevideo,1,0

## Parte 2. Base de datos

En el repositorio que acabas de clonar se encuentra la base de datos **`chinook.sqlite`**, que contiene información sobre una tienda digital de música.

La base de datos está en la carpeta **`entrada`**, dentro de **`datos`**, que a su vez se encuentra en **`ingenieria-de-datos`**.

1. Construye la ruta a la base de datos.
2. Establece una conexión utilizando **SQLite**.
3. Consulta las tablas disponibles en la base de datos.
4. Elige una de las tablas y consulta todos sus registros.
5. Muestra los datos obtenidos.
6. Cierra la conexión.

In [8]:
# Importa las bibliotecas necesarias
import sqlite3
import pandas as pd

# Construye la ruta a la base de datos
ruta = "/content/ingenieria-de-datos/datos/entrada/chinook.sqlite"

# Establece la conexión
conexion = sqlite3.connect(ruta)

# Consulta las tablas disponibles
consulta = "select * from sqlite_master where type='table';"
tablas = pd.read_sql_query(consulta, conexion) # Esta linea sirve para mandar nuestra consulta a la conexion, y el resultado es almacenado en la variable tablas, que es un dataframe.

# Muestra las tablas
tablas

# Muestra las tablas disponibles

,type,name,tbl_name,rootpage,sql
0,table,Album,Album,2,CREATE TABLE [Album]\n(\n [AlbumId] INTEGER...
1,table,Artist,Artist,3,CREATE TABLE [Artist]\n(\n [ArtistId] INTEG...
2,table,Customer,Customer,4,CREATE TABLE [Customer]\n(\n [CustomerId] I...
3,table,Employee,Employee,5,CREATE TABLE [Employee]\n(\n [EmployeeId] I...
4,table,Genre,Genre,6,CREATE TABLE [Genre]\n(\n [GenreId] INTEGER...
5,table,Invoice,Invoice,7,CREATE TABLE [Invoice]\n(\n [InvoiceId] INT...
6,table,InvoiceLine,InvoiceLine,8,CREATE TABLE [InvoiceLine]\n(\n [InvoiceLin...
7,table,MediaType,MediaType,9,CREATE TABLE [MediaType]\n(\n [MediaTypeId]...
8,table,Playlist,Playlist,10,CREATE TABLE [Playlist]\n(\n [PlaylistId] I...
9,table,PlaylistTrack,PlaylistTrack,11,CREATE TABLE [PlaylistTrack]\n(\n [Playlist...
10,table,Track,Track,13,CREATE TABLE [Track]\n(\n [TrackId] INTEGER...

In [13]:
# Elige una tabla y realiza la consulta
consulta = "select * from Album;"



# Obtén los datos
respuesta = pd.read_sql_query(consulta, conexion)



# Muestra los datos

respuesta

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

In [15]:
# Cierra la conexión
conexion.close()

## Parte 3. API

Selecciona una **API pública y gratuita diferente a las utilizadas en el laboratorio**.

La API seleccionada debe poder utilizarse **sin crear una cuenta, proporcionar información de pago o solicitar una API key**.

Investiga su documentación para identificar cómo realizar una consulta desde Python y obtén información utilizando la API seleccionada.

1. Selecciona una API pública y gratuita.
2. Consulta su documentación.
3. Identifica cómo realizar una solicitud y qué información puedes consultar.
4. Realiza una consulta desde Python.
5. Muestra el resultado obtenido.

Puedes elegir alguna de las siguientes APIs o utilizar otra que cumpla con los requisitos:

| API | Datos disponibles |
|---|---|
| [PokéAPI](https://pokeapi.co/) | Pokémon, habilidades, tipos y características |
| [Rick and Morty API](https://rickandmortyapi.com/) | Personajes, episodios y ubicaciones |
| [Dog API](https://dog.ceo/dog-api/) | Razas e imágenes de perros |
| [Nager.Date](https://date.nager.at/Api) | Días festivos de diferentes países |
| [Universities API](https://freeapihub.com/apis/universities-list) | Universidades, países, dominios y sitios web |

**Importante:** No utilices JSONPlaceholder, Open-Meteo Weather API ni NASA Open APIs, ya que fueron utilizadas en el laboratorio.

In [18]:
# Importa las bibliotecas necesarias

import requests
# Nuestro End Point
url = "http://universities.hipolabs.com/search"
# Los parámetros de nuestra consulta
params = {"country": "Mexico"}


# Envíamos nuestra consulta al End Point, junto con nuestros parámetros.
response = requests.get(url, params=params)
# La respuesta se guarda en la var response

# Condicionales
if response.status_code == 200: # El código 200 es un código que indica éxito en la operación
    universidades = response.json()
    for uni in universidades[:5]: # Mostrar las primeras 5
        print(f"Nombre: {uni['name']}")
        print(f"Dominio: {uni['domains']}")
        print("---")
else:
    print(f"Error: {response.status_code}") # En caso de que nuestra consulta no sea éxitosa, debemos conocer el código de error.

Nombre: Universidad Anáhuac
Dominio: ['anahuac.mx']
---
Nombre: Universidad de La Salle, Bajío
Dominio: ['bajio.delasalle.edu.mx']
---
Nombre: Benemerita Universidad Autónoma de Puebla
Dominio: ['buap.mx']
---
Nombre: Universidad de Guanajuato, Campus León
Dominio: ['campusleon.ugto.mx']
---
Nombre: Centro de Enseñanza Técnica Industrial
Dominio: ['ceti.mx']
---