# Laboratorio 3. Sistemas y fuentes de datos

> **Antes de comenzar**
>
> Este laboratorio está diseñado para ejecutarse en **Google Colab**.
>
> Una vez abierto en Google Colab, ejecute la primera celda para clonar el repositorio del curso y acceder a los conjuntos de datos utilizados en este laboratorio.

In [1]:
!git clone https://github.com/urendacdenisse-hub/ingenieria-de-datos.git

Cloning into 'ingenieria-de-datos'...
remote: Enumerating objects: 640, done.
remote: Counting objects: 100% (293/293), done.
remote: Compressing objects: 100% (173/173), done.
remote: Total 640 (delta 137), reused 238 (delta 98), pack-reused 347 (from 1)
Receiving objects: 100% (640/640), 127.06 MiB | 12.87 MiB/s, done.
Resolving deltas: 100% (239/239), done.

In [2]:
%cd ingenieria-de-datos

/content/ingenieria-de-datos

## Configuración inicial

Ejecuta la siguiente celda. Esta configura el entorno de trabajo y carga los recursos necesarios para que los ejemplos funcionen correctamente.

**⚠️ Importante:** No modifiques esta celda.

In [3]:
# =================================================
# 🚫 NO MODIFICAR ESTA CELDA... O SE CREASHEA
# Configura todo lo necesario para comenzar
# =================================================

import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent.parent))


En este laboratorio exploraremos diferentes formas de obtener datos y convertirlos en información que podamos utilizar para su posterior procesamiento.

Trabajaremos con:

- Archivos
- Bases de datos
- APIs
- Páginas web

# Archivos

Los archivos son una de las formas más simples de almacenar e intercambiar datos. Como vimos anteriormente, pueden utilizar diferentes formatos dependiendo del tipo de información que contienen.

En este ejemplo leeremos directamente un archivo CSV.

In [5]:
import pandas as pd

clientes = pd.read_csv("datos/entrada/clientes.csv")

clientes.head()

,id_cliente,nombre,edad,fecha_registro,ciudad,latitud,longitud,cliente_premium,saldo,correo,foto_perfil,comentario,audio_llamada,video_visita
0,1001,Ana Martínez,28,2025-01-15,Ciudad Juárez,31.6904,-106.4245,True,1520.75,ana.martinez@empresa.com,ana.jpg,Excelente atención y entrega rápida.,llamada_1001.mp3,visita_1001.mp4
1,1002,Luis Hernández,41,2025-02-03,Chihuahua,28.6353,-106.0889,False,320.40,luis.hernandez@empresa.com,luis.jpg,Solicitó cambio de domicilio.,llamada_1002.mp3,visita_1002.mp4
2,1003,María López,35,2025-02-20,Monterrey,25.6866,-100.3161,True,9870.00,maria.lopez@empresa.com,maria.jpg,Cliente frecuente desde 2022.,llamada_1003.mp3,visita_1003.mp4
3,1004,Carlos Ramírez,52,2025-03-01,Torreón,25.5390,-103.4483,False,0.00,carlos.ramirez@empresa.com,carlos.jpg,Pendiente de confirmar pedido.,llamada_1004.mp3,visita_1004.mp4
4,1005,Sofía Torres,24,2025-03-18,Hermosillo,29.0729,-110.9559,True,2450.90,sofia.torres@empresa.com,sofia.jpg,Compró durante la promoción de primavera.,llamada_1005.mp3,visita_1005.mp4

# Base de datos

Una base de datos permite almacenar y organizar información para que pueda ser consultada de manera eficiente.

En este ejemplo utilizaremos **SQLite** para conectarnos a una base de datos existente y consultar los datos almacenados en ella.

In [7]:
import sqlite3

ruta = "datos/entrada/empresa.db"

conexion = sqlite3.connect(ruta)

In [8]:
consulta = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(consulta, conexion)

          name
0     clientes
1  proveedores

In [10]:
consulta = "SELECT * FROM clientes"

clientes = pd.read_sql(consulta, conexion)

clientes

   id_cliente         nombre       ciudad    saldo
0         101      Ana López    Chihuahua  1520.50
1         102     Luis Pérez       Juárez   845.00
2         103  Sofía Ramírez    Monterrey  3200.75
3         104  Carlos Torres  Guadalajara   410.20
4         105    María Gómez    Chihuahua   980.00

In [11]:
conexion.close()

**Nota**: A diferencia de otros formatos de almacenamiento, las bases de datos se consultan mediante **SQL** (Structured Query Language), un lenguaje diseñado específicamente para crear, consultar y modificar información. En la siguiente unidad aprenderemos los fundamentos de este lenguaje.

**🔍 Explora la base de datos:** Puedes abrir el archivo `empresa.db` directamente desde tu navegador utilizando **[SQLite Viewer](https://sqliteviewer.app/)**. Solo arrastra el archivo a la página para visualizar las tablas y sus registros.

# APIs

Una API permite que una aplicación solicite información o servicios a otra aplicación.

A diferencia de un archivo local, los datos se solicitan a través de una dirección y el servidor devuelve una **respuesta**.

## JSONPlaceholder

**[JSONPlaceholder](https://jsonplaceholder.typicode.com/)** es un servicio web gratuito que simula una API real utilizando datos ficticios.

Contiene recursos como usuarios, publicaciones, comentarios y tareas, y permite realizar solicitudes para obtener estos datos en formato JSON.

En este ejemplo consultaremos la información de los usuarios disponibles.

In [12]:
import requests

url = "https://jsonplaceholder.typicode.com/users"

# Hacemos la solicitud
respuesta = requests.get(url)

# Convertimos la respuesta a JSON
datos = respuesta.json()

datos

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'address': {'street': 'Douglas Extension',
   'suite': 'Suite 847',
   'city': 'McKenziehaven',
   'zipcode': '59590-4157',
   'geo': {'lat': '-68.6102', 'lng': '-47.0653'}},
  'phone': '1-463-123-4447',
  'website': 'ramiro.info',
  'company': {'name': 'Romaguera-Jacobson',
   'catchPhrase': 'Face to face bifurcated interface',
   'bs': 'e-enable strategic applications'}},
 {'id': 4,
  'name': 'Patricia Lebsack',
  'username': 'Karianne',
  'email': 'Julianne.OConner@kory.org',
  'address': {'street': 'Hoeger Mall',
   'suite': 'Apt. 692',
   'city': 'South Elvis',
   'zipcode': '53919-4257',
   'geo': {'lat': '29.4572', 'lng': '-164.2990'}},
  'phone': '493-170-9623 x156',
  'website': 'kale.biz',
  'company': {'name': 'Robel-Corkery',
   'catchPhrase': 'Multi-tiered zero tolerance productivity',
   'bs': 'transition cutting-edge web services'}},
 {'id': 5,
  'name': 'Chelsey Dietrich',
  'username': 'Kamren',
  'email': 'Lucio_Hettinger@annie.ca',
  'address': {'street': 'Skiles Walks',
   'suite': 'Suite 351',
   'city': 'Roscoeview',
   'zipcode': '33263',
   'geo': {'lat': '-31.8129', 'lng': '62.5342'}},
  'phone': '(254)954-1289',
  'website': 'demarco.info',
  'company': {'name': 'Keebler LLC',
   'catchPhrase': 'User-centric fault-tolerant solution',
   'bs': 'revolutionize end-to-end systems'}},
 {'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'username': 'Leopoldo_Corkery',
  'email': 'Karley_Dach@jasper.info',
  'address': {'street': 'Norberto Crossing',
   'suite': 'Apt. 950',
   'city': 'South Christy',
   'zipcode': '23505-1337',
   'geo': {'lat': '-71.4197', 'lng': '71.7478'}},
  'phone': '1-477-935-8478 x6430',
  'website': 'ola.org',
  'company': {'name': 'Considine-Lockman',
   'catchPhrase': 'Synchronised bottom-line interface',
   'bs': 'e-enable innovative applications'}},
 {'id': 7,
  'name': 'Kurtis Weissnat',
  'username': 'Elwyn.Skiles',
  'email': 'Telly.Hoeger@billy.biz',
  'address': {'street': 'Rex Trail',
   'suite': 'Suite 280',
   'city': 'Howemouth',
   'zipcode': '58804-1099',
   'geo': {'lat': '24.8918', 'lng': '21.8984'}},
  'phone': '210.067.6132',
  'website': 'elvis.io',
  'company': {'name': 'Johns Group',
   'catchPhrase': 'Configurable multimedia task-force',
   'bs': 'generate enterprise e-tailers'}},
 {'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'username': 'Maxime_Nienow',
  'email': 'Sherwood@rosamond.me',
  'address': {'street': 'Ellsworth Summit',
   'suite': 'Suite 729',
   'city': 'Aliyaview',
   'zipcode': '45169',
   'geo': {'lat': '-14.3990', 'lng': '-120.7677'}},
  'phone': '586.493.6943 x140',
  'website': 'jacynthe.com',
  'company': {'name': 'Abernathy Group',
   'catchPhrase': 'Implemented secondary concept',
   'bs': 'e-enable extensible e-tailers'}},
 {'id': 9,
  'name': 'Glenna Reichert',
  'username': 'Delphine',
  'email': 'Chaim_McDermott@dana.io',
  'address': {'street': 'Dayna Park',
   'suite': 'Suite 449',
   'city': 'Bartholomebury',
   'zipcode': '76495-3109',
   'geo': {'lat': '24.6463', 'lng': '-168.8889'}},
  'phone': '(775)976-6794 x41206',
  'website': 'conrad.com',
  'company': {'name': 'Yost and Sons',
   'catchPhrase': 'Switchable contextually-based project',
   'bs': 'aggregate real-time technologies'}},
 {'id': 10,
  'name': 'Clementina DuBuque',
  'username': 'Moriah.Stanton',
  'email': 'Rey.Padberg@karina.biz',
  'address': {'street': 'Kattie Turnpike',
   'suite': 'Suite 198',
   'city': 'Lebsackbury',
   'zipcode': '31428-2261',
   'geo': {'lat': '-38.2386', 'lng': '57.2232'}},
  'phone': '024-648-3804',
  'website': 'ambrose.net',
  'company': {'name': 'Hoeger LLC',
   'catchPhrase': 'Centralized empowering task-force',
   'bs': 'target end-to-end models'}}]

In [13]:
# Convertimos el JSON en DataFrame de pandas
usuarios = pd.DataFrame(datos)

usuarios.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

## Open-Meteo

**[Open-Meteo](https://open-meteo.com/)** es un servicio que proporciona información meteorológica y pronósticos del tiempo mediante una API.

Esta API permite indicar mediante **parámetros** la ubicación y la información meteorológica que queremos consultar.

En este ejemplo solicitaremos la temperatura actual en Ciudad Juárez.

In [14]:
# Dirección de la API
url = "https://api.open-meteo.com/v1/forecast"

# Definimos los parámetros de la consulta
parametros = {
    "latitude": 31.69,
    "longitude": -106.42,
    "current": "temperature_2m"
}

# Hacemos la solicitud enviando los parámetros
respuesta = requests.get(url, params=parametros)

# Convertimos la respuesta a JSON
datos = respuesta.json()

datos

{'latitude': 31.694033,
 'longitude': -106.43187,
 'generationtime_ms': 0.016689300537109375,
 'utc_offset_seconds': 0,
 'timezone': 'GMT',
 'timezone_abbreviation': 'GMT',
 'elevation': 1127.0,
 'current_units': {'time': 'iso8601',
  'interval': 'seconds',
  'temperature_2m': '°C'},
 'current': {'time': '2026-08-18T12:00',
  'interval': 900,
  'temperature_2m': 20.3}}

Los parámetros también pueden escribirse directamente en la URL de la solicitud.

En este caso, `?` indica el inicio de los parámetros y `&` permite separar cada uno.

In [15]:
# Construimos manualmente la URL con los parámetros
url = "https://api.open-meteo.com/v1/forecast?latitude=31.69&longitude=-106.42&current=temperature_2m"

# Hacemos la solicitud
respuesta = requests.get(url)

# Convertimos la respuesta a JSON
datos = respuesta.json()

datos

{'latitude': 31.694033,
 'longitude': -106.43187,
 'generationtime_ms': 0.028133392333984375,
 'utc_offset_seconds': 0,
 'timezone': 'GMT',
 'timezone_abbreviation': 'GMT',
 'elevation': 1127.0,
 'current_units': {'time': 'iso8601',
  'interval': 'seconds',
  'temperature_2m': '°C'},
 'current': {'time': '2026-08-18T12:15',
  'interval': 900,
  'temperature_2m': 20.2}}

## NASA Open APIs

**[NASA Open APIs](https://api.nasa.gov/)** proporciona acceso a diferentes datos de la NASA mediante APIs públicas.

A diferencia de los ejemplos anteriores, algunas APIs requieren una **clave de acceso (API key)** para identificar al usuario que realiza la solicitud.

NASA proporciona una clave de demostración llamada `DEMO_KEY` que podemos utilizar para realizar consultas sencillas.

En este ejemplo consultaremos la imagen astronómica del día.

In [16]:
# Dirección de la API
url = "https://api.nasa.gov/planetary/apod"

# Definimos los parámetros de la consulta
parametros = {
    "api_key": "DEMO_KEY"
}

# Hacemos la solicitud
respuesta = requests.get(url, params=parametros)

# Convertimos la respuesta a JSON
datos = respuesta.json()

datos

{'copyright': 'Jakub Kuřák',
 'date': '2026-08-18',
 'explanation': "This was a good year for the Perseids meteor shower.  A key reason was the Moon was absent from lighting up Earth's night sky so that more meteors were visible than usual.  Where was the Moon?  It was busy visiting the Sun.  Near the Perseids peak, the Moon moved directly in front of the Sun and created a total solar eclipse visible from Greenland and Spain. The Perseids occur when the Earth collides with a stream of Sun-orbiting debris cast off by Comet Swift-Tuttle. Perseid meteors, although typically only the size of a sand grain, tend to be fast and bright because Swift-Tuttle's debris orbits the Sun in a direction partly opposite Earth's orbital motion. In the featured image compilation, accumulated over several nights from Jizerka in the Czech Republic, the Perseids meteor streaks can be traced back to a single location on the sky -- its radiant in Perseus.    Gallery: Perseids Meteor Shower of 2026",
 'hdurl': 'https://apod.nasa.gov/apod/image/2608/Perseids_karuk_3000.jpg',
 'media_type': 'image',
 'service_version': 'v1',
 'title': 'Perseids from Perseus',
 'url': 'https://apod.nasa.gov/apod/image/2608/Perseids_karuk_960.jpg'}

**Nota**: Puedes consultar la lista de parametros disponibles [aquí](https://api.nasa.gov/?search=planetary).

In [17]:
# Extraemos algunos datos de la respuesta
print("Título:", datos["title"])
print("Fecha:", datos["date"])
print("Tipo:", datos["media_type"])

Título: Perseids from Perseus
Fecha: 2026-08-18
Tipo: image

In [18]:
from IPython.display import Image, display

display(Image(url=datos["url"]))

**Nota**: Algunas APIs requieren autenticación. Una API key es una clave que permite identificar quién está realizando las solicitudes. Los requisitos de autenticación dependen de cada API.

Algunos ejemplos se muestran a continuación:

| Sitio | Uso |
|---|---|
| [YouTube Data API](https://developers.google.com/youtube/v3) | Videos, canales, playlists y comentarios |
| [Instagram API](https://developers.facebook.com/docs/instagram-platform/) | Cuentas, contenido y métricas de Instagram |
| [Reddit API](https://developers.reddit.com/docs/capabilities/server/reddit-api) | Publicaciones, comunidades y comentarios |
| [OpenAI API](https://platform.openai.com/docs/) | Modelos de inteligencia artificial para texto, imágenes y audio |
| [Gemini API](https://ai.google.dev/gemini-api/docs) | Modelos de inteligencia artificial generativa de Google |
| [Anthropic API](https://docs.anthropic.com/en/api/overview) | Acceso a los modelos Claude |
| [Spotify Web API](https://developer.spotify.com/documentation/web-api) | Artistas, álbumes, canciones y playlists |

# Páginas web

Una página web también puede utilizarse como fuente de datos. Al realizar una solicitud, normalmente recibimos un documento **HTML** que contiene tanto el contenido como la estructura de la página.

A diferencia de una API, la información no necesariamente se encuentra preparada para ser utilizada directamente como datos. Por ello, debemos identificar y extraer los elementos que nos interesan.

A este proceso se le conoce como **web scraping**.

### Books to Scrape

**Books to Scrape** es un sitio creado específicamente para practicar técnicas de web scraping.

La página contiene un catálogo ficticio de libros con información como título, precio, disponibilidad y calificación.

En este ejemplo extraeremos información directamente del contenido HTML de la página.

In [19]:
import requests

url = "https://books.toscrape.com/"

# Hacemos la solicitud
respuesta = requests.get(url)

# Obtenemos el contenido HTML
html = respuesta.text

html[:1000]

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->\n    <head>\n        <title>\n    All products | Books to Scrape - Sandbox\n</title>\n\n        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />\n        <meta name="created" content="24th Jun 2016 09:29" />\n        <meta name="description" content="" />\n        <meta name="viewport" content="width=device-width" />\n        <meta name="robots" content="NOARCHIVE,NOCACHE" />\n\n        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n        <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n\n        \n            <link rel="shortcut icon" href="static/oscar/favicon.'

**BeautifulSoup** es una biblioteca de Python que permite **interpretar y recorrer documentos HTML** para localizar y extraer elementos específicos de una página web.

Facilita tareas como buscar etiquetas, acceder a sus atributos y extraer su contenido.

In [20]:
!pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (4.16.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2

In [21]:
from bs4 import BeautifulSoup

# Interpretamos la estructura del documento HTML
pagina = BeautifulSoup(html, "html.parser")

In [22]:
# Buscamos el primer título h3
titulo = pagina.find("h3")

titulo

In [23]:
# Extraemos únicamente el texto
titulo.get_text()

'A Light in the ...'

In [24]:
# Buscamos todos los libros de la página
libros = pagina.find_all("article", class_="product_pod")

libros

[<article class="product_pod">
 <div class="image_container">
 <a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.77</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
 <div class="product_price">
 <p class="price_color">Â£53.74</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
 <div class="product_price">
 <p class="price_color">Â£50.10</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
 <div class="product_price">
 <p class="price_color">Â£47.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£54.23</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.65</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£33.34</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.93</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.60</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.15</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£13.99</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/shakespeares-sonnets_989/index.html"><img alt="Shakespeare's Sonnets" class="thumbnail" src="media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>
 <div class="product_price">
 <p class="price_color">Â£20.66</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/set-me-free_988/index.html"><img alt="Set Me Free" class="thumbnail" src="media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.46</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html"><img alt="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)" class="thumbnail" src="media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.29</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/rip-it-up-and-start-again_986/index.html"><img alt="Rip it Up and Start Again" class="thumbnail" src="media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£35.02</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html"><img alt="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991" class="thumbnail" src="media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£57.25</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/olio_984/index.html"><img alt="Olio" class="thumbnail" src="media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/olio_984/index.html" title="Olio">Olio</a></h3>
 <div class="product_price">
 <p class="price_color">Â£23.88</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html"><img alt="Mesaerion: The Best Science Fiction Stories 1800-1849" class="thumbnail" src="media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£37.59</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/libertarianism-for-beginners_982/index.html"><img alt="Libertarianism for Beginners" class="thumbnail" src="media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.33</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/its-only-the-himalayas_981/index.html"><img alt="It's Only the Himalayas" class="thumbnail" src="media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
 <div class="product_price">
 <p class="price_color">Â£45.17</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>]

In [25]:
# Extraccion de información

titulo = libros[0].find("h3").get_text()
precio = libros[0].find("p", class_="price_color").get_text()
disponibilidad = libros[0].find("p", class_="instock availability").get_text()

print(titulo)
print(precio)
print(disponibilidad)

A Light in the ...
Â£51.77



        In stock

In [26]:
# Formateo de informacion
precio = float(precio[2:])
disponibilidad = disponibilidad.strip()

print(precio)
print(disponibilidad)

51.77
In stock

In [27]:
lista_articulos = []

for libro in libros:
    titulo = libro.find("h3").get_text()
    precio = float(libro.find("p", class_="price_color").get_text()[2:])
    disponibilidad = libro.find("p", class_="instock availability").get_text().strip()

    lista_articulos.append((titulo, precio, disponibilidad))

In [28]:
lista_articulos

[('A Light in the ...', 51.77, 'In stock'),
 ('Tipping the Velvet', 53.74, 'In stock'),
 ('Soumission', 50.1, 'In stock'),
 ('Sharp Objects', 47.82, 'In stock'),
 ('Sapiens: A Brief History ...', 54.23, 'In stock'),
 ('The Requiem Red', 22.65, 'In stock'),
 ('The Dirty Little Secrets ...', 33.34, 'In stock'),
 ('The Coming Woman: A ...', 17.93, 'In stock'),
 ('The Boys in the ...', 22.6, 'In stock'),
 ('The Black Maria', 52.15, 'In stock'),
 ('Starving Hearts (Triangular Trade ...', 13.99, 'In stock'),
 ("Shakespeare's Sonnets", 20.66, 'In stock'),
 ('Set Me Free', 17.46, 'In stock'),
 ("Scott Pilgrim's Precious Little ...", 52.29, 'In stock'),
 ('Rip it Up and ...', 35.02, 'In stock'),
 ('Our Band Could Be ...', 57.25, 'In stock'),
 ('Olio', 23.88, 'In stock'),
 ('Mesaerion: The Best Science ...', 37.59, 'In stock'),
 ('Libertarianism for Beginners', 51.33, 'In stock'),
 ("It's Only the Himalayas", 45.17, 'In stock')]

In [29]:
articulos = pd.DataFrame(
    lista_articulos,
    columns=["titulo", "precio", "disponibilidad"]
)

articulos

                                   titulo  precio disponibilidad
0                      A Light in the ...   51.77       In stock
1                      Tipping the Velvet   53.74       In stock
2                              Soumission   50.10       In stock
3                           Sharp Objects   47.82       In stock
4            Sapiens: A Brief History ...   54.23       In stock
5                         The Requiem Red   22.65       In stock
6            The Dirty Little Secrets ...   33.34       In stock
7                 The Coming Woman: A ...   17.93       In stock
8                     The Boys in the ...   22.60       In stock
9                         The Black Maria   52.15       In stock
10  Starving Hearts (Triangular Trade ...   13.99       In stock
11                  Shakespeare's Sonnets   20.66       In stock
12                            Set Me Free   17.46       In stock
13    Scott Pilgrim's Precious Little ...   52.29       In stock
14                      Rip it Up and ...   35.02       In stock
15                  Our Band Could Be ...   57.25       In stock
16                                   Olio   23.88       In stock
17        Mesaerion: The Best Science ...   37.59       In stock
18           Libertarianism for Beginners   51.33       In stock
19                It's Only the Himalayas   45.17       In stock

# Resumen del laboratorio

En este laboratorio obtuvimos datos desde diferentes fuentes y observamos que **la forma de acceder a ellos depende del sistema que los proporciona**.

Trabajamos con:

- **Archivos:** lectura directa de datos almacenados localmente.
- **Bases de datos:** conexión y consulta de información mediante SQL.
- **APIs:** solicitud de datos a servicios externos.
- **Páginas web:** extracción de información desde documentos HTML mediante web scraping.

Aunque las fuentes y los métodos de acceso fueron diferentes, en todos los casos pudimos obtener datos y llevarlos a una estructura que puede ser utilizada para su procesamiento y análisis.

## Ideas clave

- Los datos pueden provenir de diferentes fuentes.
- Cada fuente requiere diferentes mecanismos de acceso.
- Las bases de datos permiten consultar únicamente la información necesaria.
- Las APIs definen sus propias reglas, parámetros y mecanismos de autenticación.
- Una página web puede utilizarse como fuente de datos mediante web scraping.
- Los datos obtenidos pueden requerir transformación antes de poder utilizarlos.

# Actividad

En esta actividad obtendrás datos utilizando **tres mecanismos diferentes de acceso**: archivos, bases de datos y APIs.

👉 Haz clic aquí para abrir la actividad:

**[Actividad 03 - Acceso a diferentes fuentes de datos](https://colab.research.google.com/github/urendacdenisse-hub/ingenieria-de-datos/blob/main/actividades/unidad-01/actividad-03.ipynb)**